#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define CAN_TX_PIN GPIO_NUM_21
#define CAN_RX_PIN GPIO_NUM_20
#define CAN_SPEED TWAI_TIMING_CONFIG_1MBITS
#define CAN_CONFIG TWAI_FILTER_CONFIG_ACCEPT_ALL
#define CAN_MODE TWAI_MODE_NORMAL
#define UNIQUE_NAME "ESP32C3_DroneCAN"
#define CAN_READ_TIMEOUT_MS 10

#endif